import Avatar00 from "../../assets/avatar/avatar-00.svg"
import Avatar01 from "../../assets/avatar/avatar-01.svg"
import Avatar02 from "../../assets/avatar/avatar-02.svg"
import Avatar03 from "../../assets/avatar/avatar-03.svg"
import Avatar04 from "../../assets/avatar/avatar-04.svg"
import Avatar05 from "../../assets/avatar/avatar-05.svg"
import Avatar06 from "../../assets/avatar/avatar-06.svg"
import Avatar07 from "../../assets/avatar/avatar-07.svg"
import Avatar08 from "../../assets/avatar/avatar-08.svg"
import Avatar09 from "../../assets/avatar/avatar-09.svg"
import Avatar10 from "../../assets/avatar/avatar-10.svg"
import Avatar11 from "../../assets/avatar/avatar-11.svg"
import Avatar12 from "../../assets/avatar/avatar-12.svg"
import Avatar13 from "../../assets/avatar/avatar-13.svg"
import Avatar14 from "../../assets/avatar/avatar-14.svg"
import Avatar15 from "../../assets/avatar/avatar-15.svg"
import Avatar16 from "../../assets/avatar/avatar-16.svg"
import Avatar17 from "../../assets/avatar/avatar-17.svg"
import Avatar18 from "../../assets/avatar/avatar-18.svg"
import Avatar19 from "../../assets/avatar/avatar-19.svg"
import Avatar20 from "../../assets/avatar/avatar-20.svg"
import Avatar21 from "../../assets/avatar/avatar-21.svg"
import Avatar22 from "../../assets/avatar/avatar-22.svg"
import Avatar23 from "../../assets/avatar/avatar-23.svg"
import Avatar24 from "../../assets/avatar/avatar-24.svg"
import Avatar25 from "../../assets/avatar/avatar-25.svg"
import Avatar26 from "../../assets/avatar/avatar-26.svg"
import Avatar27 from "../../assets/avatar/avatar-27.svg"
import Avatar28 from "../../assets/avatar/avatar-28.svg"
import Avatar29 from "../../assets/avatar/avatar-29.svg"
import Avatar30 from "../../assets/avatar/avatar-30.svg"
import Avatar31 from "../../assets/avatar/avatar-31.svg"
import Avatar32 from "../../assets/avatar/avatar-32.svg"
import Avatar33 from "../../assets/avatar/avatar-33.svg"
import Avatar34 from "../../assets/avatar/avatar-34.svg"
import Avatar35 from "../../assets/avatar/avatar-35.svg"
import Avatar36 from "../../assets/avatar/avatar-36.svg"
import Avatar37 from "../../assets/avatar/avatar-37.svg"
import Avatar38 from "../../assets/avatar/avatar-38.svg"
import Avatar39 from "../../assets/avatar/avatar-39.svg"
import Avatar40 from "../../assets/avatar/avatar-40.svg"
import Avatar41 from "../../assets/avatar/avatar-41.svg"
import Avatar42 from "../../assets/avatar/avatar-42.svg"
import Avatar43 from "../../assets/avatar/avatar-43.svg"
import Avatar44 from "../../assets/avatar/avatar-44.svg"
import Avatar45 from "../../assets/avatar/avatar-45.svg"
import Avatar46 from "../../assets/avatar/avatar-46.svg"
import Avatar47 from "../../assets/avatar/avatar-47.svg"
import Avatar48 from "../../assets/avatar/avatar-48.svg"
import Avatar49 from "../../assets/avatar/avatar-49.svg"
import Avatar50 from "../../assets/avatar/avatar-50.svg"
import Avatar51 from "../../assets/avatar/avatar-51.svg"
import Avatar52 from "../../assets/avatar/avatar-52.svg"
import Avatar53 from "../../assets/avatar/avatar-53.svg"
import Avatar54 from "../../assets/avatar/avatar-54.svg"
import Avatar55 from "../../assets/avatar/avatar-55.svg"
import Avatar56 from "../../assets/avatar/avatar-56.svg"
import Avatar57 from "../../assets/avatar/avatar-57.svg"
import Avatar58 from "../../assets/avatar/avatar-58.svg"
import Avatar59 from "../../assets/avatar/avatar-59.svg"
import Avatar60 from "../../assets/avatar/avatar-60.svg"
import Avatar61 from "../../assets/avatar/avatar-61.svg"
import Avatar62 from "../../assets/avatar/avatar-62.svg"
import Avatar63 from "../../assets/avatar/avatar-63.svg"
import Avatar64 from "../../assets/avatar/avatar-64.svg"
import Avatar65 from "../../assets/avatar/avatar-65.svg"
import Avatar66 from "../../assets/avatar/avatar-66.svg"
import Avatar67 from "../../assets/avatar/avatar-67.svg"
import Avatar68 from "../../assets/avatar/avatar-68.svg"
import Avatar69 from "../../assets/avatar/avatar-69.svg"
import Avatar70 from "../../assets/avatar/avatar-70.svg"
import Avatar71 from "../../assets/avatar/avatar-71.svg"
import Avatar72 from "../../assets/avatar/avatar-72.svg"
import Avatar73 from "../../assets/avatar/avatar-73.svg"
import Avatar74 from "../../assets/avatar/avatar-74.svg"
import Avatar75 from "../../assets/avatar/avatar-75.svg"
import Avatar76 from "../../assets/avatar/avatar-76.svg"
import Avatar77 from "../../assets/avatar/avatar-77.svg"

export const SliderData = [
    Avatar00, Avatar01, Avatar02, Avatar03, Avatar04, Avatar05, Avatar06, Avatar07, Avatar08, Avatar09,
    Avatar10, Avatar11, Avatar12, Avatar13, Avatar14, Avatar15, Avatar16, Avatar17, Avatar18, Avatar19,
    Avatar20, Avatar21, Avatar22, Avatar23, Avatar24, Avatar25, Avatar26, Avatar27, Avatar28, Avatar29,
    Avatar30, Avatar31, Avatar32, Avatar33, Avatar34, Avatar35, Avatar36, Avatar37, Avatar38, Avatar39,
    Avatar40, Avatar41, Avatar42, Avatar43, Avatar44, Avatar45, Avatar46, Avatar47, Avatar48, Avatar49,
    Avatar50, Avatar51, Avatar52, Avatar53, Avatar54, Avatar55, Avatar56, Avatar57, Avatar58, Avatar59,
    Avatar60, Avatar61, Avatar62, Avatar63, Avatar64, Avatar65, Avatar66, Avatar67, Avatar68, Avatar69,
    Avatar70, Avatar71, Avatar72, Avatar73, Avatar74, Avatar75, Avatar76, Avatar77]

export default SliderData